import type { Metadata } from "next";
import "@mantine/core/styles.layer.css";

import localFont from "next/font/local";

import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import { MantineProvider } from "@mantine/core";
import { theme } from "@/src/components/ui/theme";
import Header from "@/src/components/layout/header";
import Footer from "@/src/components/layout/footer";

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});

// Add your custom font here

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${instrumentSans.variable}  antialiased`}>
        <MantineProvider theme={theme}>
          <main className="flex flex-col ">
            <Header />
            {children}
            <Footer />
          </main>
        </MantineProvider>
      </body>
    </html>
  );
}
