import type { Metadata } from "next";
import "@mantine/core/styles.layer.css";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import { MantineProvider } from "@mantine/core";
import { theme } from "@/src/components/ui/theme";
import Header from "@/src/components/layout/header";
import Footer from "@/src/components/layout/footer";
import Script from "next/script";

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});

// Add your custom font here

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics */}
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-4S4GPFNQC2"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-4S4GPFNQC2');
          `}
        </Script>
      </head>
      <body className={`${instrumentSans.variable}  antialiased`}>
        <MantineProvider theme={theme}>
          <script
            type="text/javascript"
            id="hs-script-loader"
            async
            defer
            src="//js-eu1.hs-scripts.com/146771318.js"
          >
            <main className="flex flex-col ">
              <Header />
              {children}
              <Footer />
            </main>
          </script>
        </MantineProvider>
      </body>
    </html>
  );
}
